// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1wLmeWorb-gaGfP0FRwNBaIVvdwAZds',
    appId: '1:171026127222:android:d979618fb576640d588257',
    messagingSenderId: '171026127222',
    projectId: 'test-72c80',
    storageBucket: 'test-72c80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3dbvLlT5AY4GbLuBaoV3Hz_f--ZthVMw',
    appId: '1:171026127222:ios:940b605e91973ab7588257',
    messagingSenderId: '171026127222',
    projectId: 'test-72c80',
    storageBucket: 'test-72c80.firebasestorage.app',
    iosBundleId: 'com.example.liveScore',
  );
}
